### ISSUE TITLE
Guess a note

### ISSUE THREAD

**Issue by leehbi** [txels/fretboard#6]
I've created a basic 'guess a note' game using the lib.  I can give you a pull request for this if you wish.  It isn't much but shows how the library can be used.

I was also thinking of developing an ear training game too but this will take more effort.

**Comment by txels** [comment]
Hey, that sounds great. Maybe we can create a folder with code samples.

Or if you have this running somewhere maybe it will be enough to add a *showcase* section in the README in the form of links to live examples.

**Comment by leehbi** [comment]
I've cloned your repo and added a GuessNotes.html.  Please excuse my JS skills I'm only a part-time hacker :-) https://github.com/leehbi/GuitarTraining

**Comment by txels** [comment]
That's nice! I realise that a "feature" of my library is that notes have titles, so it will show you the note on hover, which allows for cheating in your game 😅 

I will make that behaviour optional and not the default.

I will also look at how to make the library available via a URL and an NPM package so that you don't need to copy the source code :)

**Comment by txels** [comment]
I just made a change so that the note name won't display on hover by default, but can be made to via options: 
https://github.com/txels/fretboard/commit/8a609399b155205a32e512691e6536cc8f85aa30

**Comment by leehbi** [comment]
Great - I've added toggle button so the game player can turn it off.    Think if I take this further I will have to use a react like framework as state is already getting tricky.  Javascript is still a royal pain.

**Comment by txels** [comment]
As far as frameworks go, I'm using [Vue](https://vuejs.org/) a lot these days. It's really nice, you may want to give it a try. And there's loads of good learning material, e.g.: https://www.vuemastery.com/courses-path/beginner

**Comment by txels** [comment]
BTW I just published the package on NPM: https://www.npmjs.com/package/fretboards - now you can use it from CDN rather than having to keep a local copy.

**Comment by leehbi** [comment]
Thanks for publishing to NPM.  I've created a game using React JS   https://github.com/leehbi/Fretty

I will look for a place to publish to.   I hope to add more games to it.    I will learn Vue for another app as I started to learn React a few months ago.
